
spring:
  application:
     name: api-gateway

  cloud:
    gateway:
       routes:
         - id: aadhar-service
           uri: lb://AADHAR-SERVICE
           predicates:
             - Path=/api/v1/aadhar/**
                            
           filters:
             - StripPrefix=2
             
         - id: user-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/api/v1/users/**
                            
           filters:
             - StripPrefix=2

         - id: education-service
           uri: lb://EDUCATION-SERVICE
           predicates:
             - Path=/api/v1/education/**
                            
           filters:
             - StripPrefix=2
             
         - id: pan-service
           uri: lb://PAN-SERVICE
           predicates:
             - Path=/api/v1/pan/**

           filters:
             - StripPrefix=2

eureka:
   client:
     service-url:
        defaultZone: http://localhost:8761/eureka


server:
  port: 8010